version: 0.2
env:
  variables:
    S3_BUCKET: "testbuyer"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
    
  build:
    commands:
      - echo Build started on `date`
      - npm run build:prod 
  post_build:
     commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://my-awsome-bucket-of-files --delete
